spring:
  application:
    name: music-lab

  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://172.17.0.2:5432/iam
    url: jdbc:postgresql://musiclabdb.cjkmsui00tjv.ap-south-1.rds.amazonaws.com:5432/musiclabdb
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.xml
  banner:
    location: classpath:/banner.txt
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG